// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations.v3
{
    [DbContext(typeof(AEUContext))]
    [Migration("20251223024009_InitialCreateV3")]
    partial class InitialCreateV3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Concrete.OzlukEntities.Kullanici", b =>
                {
                    b.Property<Guid>("KullaniciUuid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("kullanici_uuid")
                        .HasDefaultValueSql("UUID()");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ad");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("guncelleme_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("GuncellemeTarihi"));

                    b.Property<string>("KullaniciTipi")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("ENUM('OGRENCI', 'AKADEMISYEN', 'PERSONEL')")
                        .HasColumnName("kullanici_tipi")
                        .HasDefaultValueSql("'OGRENCI'");

                    b.Property<string>("KurumEposta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("kurum_eposta");

                    b.Property<string>("KurumSicilNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("kurum_sicil_no");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("OrtaAd")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("orta_ad");

                    b.Property<string>("ParolaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("parola_hash");

                    b.Property<string>("ParolaTuz")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("parola_tuz");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("soyad");

                    b.HasKey("KullaniciUuid");

                    b.HasIndex("KurumEposta")
                        .IsUnique()
                        .HasDatabaseName("UK_Kullanicilar_KurumEposta");

                    b.HasIndex("KurumSicilNo")
                        .IsUnique()
                        .HasDatabaseName("UK_Kullanicilar_KurumSicilNo");

                    b.ToTable("kullanicilar", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Kullanicilar_KurumEpostaDomain", "kurum_eposta LIKE '%@ahievran.edu.tr'");
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.YetkiEntities.IslemYetkisi", b =>
                {
                    b.Property<Guid>("IslemYetkisiUuid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("islem_yetkisi_uuid")
                        .HasDefaultValueSql("UUID()");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("aciklama");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("guncelleme_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("GuncellemeTarihi"));

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("YetkiAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("yetki_adi");

                    b.HasKey("IslemYetkisiUuid");

                    b.ToTable("islem_yetkileri", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Concrete.YetkiEntities.KullaniciIslemYetkisi", b =>
                {
                    b.Property<Guid>("YetkiAtamaUuid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("yetki_atama_uuid")
                        .HasDefaultValueSql("UUID()");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("guncelleme_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("GuncellemeTarihi"));

                    b.Property<Guid>("IslemYetkisiUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("islem_yetkisi_uuid");

                    b.Property<Guid>("KullaniciUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("kullanici_uuid");

                    b.Property<Guid?>("KullaniciUuid1")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("YetkiVerenUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("yetki_veren_uuid");

                    b.HasKey("YetkiAtamaUuid");

                    b.HasIndex("IslemYetkisiUuid")
                        .HasDatabaseName("IX_KullaniciIslemYetkisi_IslemYetkisiUuid");

                    b.HasIndex("KullaniciUuid")
                        .HasDatabaseName("IX_KullaniciIslemYetkisi_KullaniciUuid");

                    b.HasIndex("KullaniciUuid1");

                    b.HasIndex("YetkiVerenUuid")
                        .HasDatabaseName("IX_KullaniciIslemYetkisi_YetkiVerenUuid");

                    b.ToTable("kullanici_islem_yetkisi", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.DersEntities.AkademisyenDersAtama", b =>
                {
                    b.Property<Guid>("AtamaUuid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("atama_uuid")
                        .HasDefaultValueSql("UUID()");

                    b.Property<Guid?>("AkademisyenKullaniciUuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AkademisyenUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("akademisyen_uuid");

                    b.Property<Guid>("DersUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("ders_uuid");

                    b.Property<Guid?>("DersUuid1")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("guncelleme_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("GuncellemeTarihi"));

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("AtamaUuid");

                    b.HasIndex("AkademisyenKullaniciUuid");

                    b.HasIndex("DersUuid");

                    b.HasIndex("DersUuid1");

                    b.HasIndex("AkademisyenUuid", "DersUuid")
                        .IsUnique()
                        .HasDatabaseName("UK_Akademisyen_Ders");

                    b.ToTable("akademisyen_ders_atamalari", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.DersEntities.Ders", b =>
                {
                    b.Property<Guid>("DersUuid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("ders_uuid")
                        .HasDefaultValueSql("UUID()");

                    b.Property<string>("Aciklama")
                        .HasColumnType("longtext")
                        .HasColumnName("aciklama");

                    b.Property<int>("Akts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("akts");

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ders_adi");

                    b.Property<string>("DersKodu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ders_kodu");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("guncelleme_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("GuncellemeTarihi"));

                    b.Property<int>("HaftalikDersSaati")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("haftalik_ders_saati");

                    b.Property<int>("Kredi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("kredi");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("DersUuid");

                    b.HasIndex("DersKodu")
                        .IsUnique()
                        .HasDatabaseName("UK_Dersler_DersKodu");

                    b.ToTable("dersler", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.DersEntities.Not", b =>
                {
                    b.Property<Guid>("NotUuid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("not_uuid")
                        .HasDefaultValueSql("UUID()");

                    b.Property<int>("AlinanPuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("alinan_puan")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("guncelleme_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("GuncellemeTarihi"));

                    b.Property<Guid?>("OgrenciKullaniciUuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OgrenciUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("ogrenci_uuid");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("SinavUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("sinav_uuid");

                    b.Property<Guid?>("SinavUuid1")
                        .HasColumnType("char(36)");

                    b.HasKey("NotUuid");

                    b.HasIndex("OgrenciKullaniciUuid");

                    b.HasIndex("OgrenciUuid");

                    b.HasIndex("SinavUuid1");

                    b.HasIndex("SinavUuid", "OgrenciUuid")
                        .IsUnique()
                        .HasDatabaseName("UK_Notlar_Sinav_Ogrenci");

                    b.ToTable("notlar", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.DersEntities.OgrenciDersKayit", b =>
                {
                    b.Property<Guid>("KayitUuid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("kayit_uuid")
                        .HasDefaultValueSql("UUID()");

                    b.Property<Guid>("DersUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("ders_uuid");

                    b.Property<Guid?>("DersUuid1")
                        .HasColumnType("char(36)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("ENUM('DEVAMEDIYOR','GECTI','KALDI')")
                        .HasDefaultValue("DEVAMEDIYOR")
                        .HasColumnName("durum");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("guncelleme_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("GuncellemeTarihi"));

                    b.Property<Guid?>("OgrenciKullaniciUuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("OgrenciUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("ogrenci_uuid");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("KayitUuid");

                    b.HasIndex("DersUuid");

                    b.HasIndex("DersUuid1");

                    b.HasIndex("OgrenciKullaniciUuid");

                    b.HasIndex("OgrenciUuid", "DersUuid")
                        .IsUnique()
                        .HasDatabaseName("UK_Ogrenci_Ders");

                    b.ToTable("ogrenci_ders_kayitlari", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.DersEntities.Sinav", b =>
                {
                    b.Property<Guid>("SinavUuid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("sinav_uuid")
                        .HasDefaultValueSql("UUID()");

                    b.Property<Guid>("DersUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("ders_uuid");

                    b.Property<Guid?>("DersUuid1")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("guncelleme_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("GuncellemeTarihi"));

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("SinavAgirligi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("sinav_agirligi")
                        .HasDefaultValueSql("0.00");

                    b.Property<DateTime>("SinavTarih")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("sinav_tarihi")
                        .HasDefaultValueSql("UTC_DATE()");

                    b.Property<string>("SinavTipi")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("ENUM('QUIZ','VIZE','FINAL','PROJE','BUTUNLEME')")
                        .HasColumnName("sinav_tipi")
                        .HasDefaultValueSql("'QUIZ'");

                    b.Property<int>("ToplamPuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("toplam_puan")
                        .HasDefaultValueSql("100");

                    b.HasKey("SinavUuid");

                    b.HasIndex("DersUuid");

                    b.HasIndex("DersUuid1");

                    b.ToTable("sinavlar", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.FakulteEntities.AkademisyenBolumAtama", b =>
                {
                    b.Property<Guid>("AtamaUuid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("bolum_atama_uuid")
                        .HasDefaultValueSql("UUID()");

                    b.Property<Guid?>("AkademisyenKullaniciUuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BolumUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("bolum_uuid");

                    b.Property<Guid?>("BolumUuid1")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("guncelleme_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("GuncellemeTarihi"));

                    b.Property<Guid>("KullaniciUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("kullanici_uuid");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("AtamaUuid");

                    b.HasIndex("AkademisyenKullaniciUuid");

                    b.HasIndex("BolumUuid");

                    b.HasIndex("BolumUuid1");

                    b.HasIndex("KullaniciUuid", "BolumUuid")
                        .IsUnique()
                        .HasDatabaseName("UK_AkademisyenBolumAtama_Kullanici_Bolum");

                    b.ToTable("akademisyen_bolum_atamalari", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.FakulteEntities.AnaDal", b =>
                {
                    b.Property<Guid>("AnaDalUuid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("ana_dal_uuid")
                        .HasDefaultValueSql("UUID()");

                    b.Property<string>("AnaDalAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("ana_dal_ad");

                    b.Property<Guid>("FakulteUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("fakulte_uuid");

                    b.Property<Guid?>("FakulteUuid1")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("guncelleme_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("GuncellemeTarihi"));

                    b.Property<DateTime>("KurulusTarihi")
                        .HasColumnType("date")
                        .HasColumnName("kurulus_tarihi");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("AnaDalUuid");

                    b.HasIndex("FakulteUuid");

                    b.HasIndex("FakulteUuid1");

                    b.ToTable("ana_dallar", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.FakulteEntities.Bolum", b =>
                {
                    b.Property<Guid>("BolumUuid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("bolum_uuid")
                        .HasDefaultValueSql("UUID()");

                    b.Property<Guid>("AnaDalUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("ana_dal_uuid");

                    b.Property<Guid?>("AnaDalUuid1")
                        .HasColumnType("char(36)");

                    b.Property<string>("BolumAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("bolum_ad");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("guncelleme_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("GuncellemeTarihi"));

                    b.Property<DateTime>("KurulusTarihi")
                        .HasColumnType("date")
                        .HasColumnName("kurulus_tarihi");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("BolumUuid");

                    b.HasIndex("AnaDalUuid");

                    b.HasIndex("AnaDalUuid1");

                    b.ToTable("bolumler", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.FakulteEntities.Fakulte", b =>
                {
                    b.Property<Guid>("FakulteUuid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("fakulte_uuid")
                        .HasDefaultValueSql("UUID()");

                    b.Property<string>("FakulteAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("fakulte_ad");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("guncelleme_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("GuncellemeTarihi"));

                    b.Property<DateTime>("KurulusTarihi")
                        .HasColumnType("date")
                        .HasColumnName("kurulus_tarihi");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("WebAdres")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("web_adres");

                    b.HasKey("FakulteUuid");

                    b.ToTable("fakulteler", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.FakulteEntities.OgrenciBolumKayit", b =>
                {
                    b.Property<Guid>("BolumKayitUuid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("bolum_kayit_uuid")
                        .HasDefaultValueSql("UUID()");

                    b.Property<Guid>("BolumUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("bolum_uuid");

                    b.Property<Guid?>("BolumUuid1")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("guncelleme_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("GuncellemeTarihi"));

                    b.Property<Guid>("KullaniciUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("kullanici_uuid");

                    b.Property<Guid?>("OgrenciKullaniciUuid")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("BolumKayitUuid");

                    b.HasIndex("BolumUuid");

                    b.HasIndex("BolumUuid1");

                    b.HasIndex("OgrenciKullaniciUuid");

                    b.HasIndex("KullaniciUuid", "BolumUuid")
                        .IsUnique()
                        .HasDatabaseName("UK_OgrenciBolumKayit_Kullanici_Bolum");

                    b.ToTable("ogrenci_bolum_kayitlari", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.OzlukEntities.Adres", b =>
                {
                    b.Property<Guid>("AdresUuid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("adres_uuid")
                        .HasDefaultValueSql("UUID()");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("guncelleme_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("GuncellemeTarihi"));

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ilce");

                    b.Property<Guid>("KullaniciUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("kullanici_uuid");

                    b.Property<Guid?>("KullaniciUuid1")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Oncelikli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("oncelikli");

                    b.Property<string>("PostaKodu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("posta_kodu");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sehir");

                    b.Property<string>("Sokak")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sokak");

                    b.Property<string>("Ulke")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ulke");

                    b.HasKey("AdresUuid");

                    b.HasIndex("KullaniciUuid1");

                    b.HasIndex("KullaniciUuid", "Oncelikli")
                        .IsUnique()
                        .HasDatabaseName("UK_OncelikliAdres");

                    b.ToTable("adresler", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.OzlukEntities.Eposta", b =>
                {
                    b.Property<Guid>("EpostaUuid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("eposta_uuid")
                        .HasDefaultValueSql("UUID()");

                    b.Property<string>("EpostaAdresi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("eposta_adresi");

                    b.Property<string>("EpostaTipi")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("ENUM('KISISEL','IS','DIGER')")
                        .HasColumnName("eposta_tipi")
                        .HasDefaultValueSql("'KISISEL'");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("guncelleme_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("GuncellemeTarihi"));

                    b.Property<Guid>("KullaniciUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("kullanici_uuid");

                    b.Property<Guid?>("KullaniciUuid1")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Oncelikli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("oncelikli");

                    b.HasKey("EpostaUuid");

                    b.HasIndex("EpostaAdresi")
                        .IsUnique()
                        .HasDatabaseName("UK_Epostalar_EpostaAdresi");

                    b.HasIndex("KullaniciUuid1");

                    b.HasIndex("KullaniciUuid", "Oncelikli")
                        .IsUnique()
                        .HasDatabaseName("UK_OncelikliEposta");

                    b.ToTable("epostalar", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.OzlukEntities.Telefon", b =>
                {
                    b.Property<Guid>("TelefonUuid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("telefon_uuid")
                        .HasDefaultValueSql("UUID()");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("guncelleme_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("GuncellemeTarihi"));

                    b.Property<Guid>("KullaniciUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("kullanici_uuid");

                    b.Property<Guid?>("KullaniciUuid1")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Oncelikli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("oncelikli");

                    b.Property<string>("TelefonNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefon_numarasi");

                    b.Property<string>("TelefonTipi")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("ENUM('CEP','EV','IS','DIGER')")
                        .HasColumnName("telefon_tipi")
                        .HasDefaultValueSql("'CEP'");

                    b.Property<string>("UlkeKodu")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("ulke_kodu");

                    b.HasKey("TelefonUuid");

                    b.HasIndex("KullaniciUuid1");

                    b.HasIndex("KullaniciUuid", "Oncelikli")
                        .IsUnique()
                        .HasDatabaseName("UK_OncelikliTelefon");

                    b.HasIndex("KullaniciUuid", "TelefonNo")
                        .IsUnique()
                        .HasDatabaseName("UK_Telefonlar_Kullanici_Telefon");

                    b.ToTable("telefonlar", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Concrete.YetkiEntities.KullaniciIslemYetkisi", b =>
                {
                    b.HasOne("Core.Entities.Concrete.YetkiEntities.IslemYetkisi", "IslemYetkisi")
                        .WithMany("KullaniciIslemYetkileri")
                        .HasForeignKey("IslemYetkisiUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KullaniciIslemYetkisi_IslemYetkileri");

                    b.HasOne("Core.Entities.Concrete.OzlukEntities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KullaniciIslemYetkisi_Kullanicilar");

                    b.HasOne("Core.Entities.Concrete.OzlukEntities.Kullanici", null)
                        .WithMany("KullaniciIslemYetkileri")
                        .HasForeignKey("KullaniciUuid1");

                    b.HasOne("Core.Entities.Concrete.OzlukEntities.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("YetkiVerenUuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_KullaniciIslemYetkisi_YetkiVeren");

                    b.Navigation("IslemYetkisi");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Entities.Concrete.DersEntities.AkademisyenDersAtama", b =>
                {
                    b.HasOne("Core.Entities.Concrete.OzlukEntities.Kullanici", "Akademisyen")
                        .WithMany()
                        .HasForeignKey("AkademisyenKullaniciUuid");

                    b.HasOne("Core.Entities.Concrete.OzlukEntities.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("AkademisyenUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AkademisyenAtama_Kullanicilar");

                    b.HasOne("Entities.Concrete.DersEntities.Ders", null)
                        .WithMany()
                        .HasForeignKey("DersUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AkademisyenAtama_Dersler");

                    b.HasOne("Entities.Concrete.DersEntities.Ders", "Ders")
                        .WithMany("AkademisyenDersAtamalari")
                        .HasForeignKey("DersUuid1");

                    b.Navigation("Akademisyen");

                    b.Navigation("Ders");
                });

            modelBuilder.Entity("Entities.Concrete.DersEntities.Not", b =>
                {
                    b.HasOne("Core.Entities.Concrete.OzlukEntities.Kullanici", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciKullaniciUuid");

                    b.HasOne("Core.Entities.Concrete.OzlukEntities.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("OgrenciUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notlar_Kullanicilar");

                    b.HasOne("Entities.Concrete.DersEntities.Sinav", null)
                        .WithMany()
                        .HasForeignKey("SinavUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notlar_Sinavlar");

                    b.HasOne("Entities.Concrete.DersEntities.Sinav", "Sinav")
                        .WithMany("Notlar")
                        .HasForeignKey("SinavUuid1");

                    b.Navigation("Ogrenci");

                    b.Navigation("Sinav");
                });

            modelBuilder.Entity("Entities.Concrete.DersEntities.OgrenciDersKayit", b =>
                {
                    b.HasOne("Entities.Concrete.DersEntities.Ders", null)
                        .WithMany()
                        .HasForeignKey("DersUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OgrenciKayit_Dersler");

                    b.HasOne("Entities.Concrete.DersEntities.Ders", "Ders")
                        .WithMany("OgrenciKayitlari")
                        .HasForeignKey("DersUuid1");

                    b.HasOne("Core.Entities.Concrete.OzlukEntities.Kullanici", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciKullaniciUuid");

                    b.HasOne("Core.Entities.Concrete.OzlukEntities.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("OgrenciUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OgrenciKayit_Kullanicilar");

                    b.Navigation("Ders");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("Entities.Concrete.DersEntities.Sinav", b =>
                {
                    b.HasOne("Entities.Concrete.DersEntities.Ders", null)
                        .WithMany()
                        .HasForeignKey("DersUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Sinavlar_Dersler");

                    b.HasOne("Entities.Concrete.DersEntities.Ders", "Ders")
                        .WithMany("Sinavlar")
                        .HasForeignKey("DersUuid1");

                    b.Navigation("Ders");
                });

            modelBuilder.Entity("Entities.Concrete.FakulteEntities.AkademisyenBolumAtama", b =>
                {
                    b.HasOne("Core.Entities.Concrete.OzlukEntities.Kullanici", "Akademisyen")
                        .WithMany()
                        .HasForeignKey("AkademisyenKullaniciUuid");

                    b.HasOne("Entities.Concrete.FakulteEntities.Bolum", null)
                        .WithMany()
                        .HasForeignKey("BolumUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AkademisyenBolumAtama_Bolumler");

                    b.HasOne("Entities.Concrete.FakulteEntities.Bolum", "Bolum")
                        .WithMany("AkademisyenAtamalari")
                        .HasForeignKey("BolumUuid1");

                    b.HasOne("Core.Entities.Concrete.OzlukEntities.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("KullaniciUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AkademisyenBolumAtama_Kullanicilar");

                    b.Navigation("Akademisyen");

                    b.Navigation("Bolum");
                });

            modelBuilder.Entity("Entities.Concrete.FakulteEntities.AnaDal", b =>
                {
                    b.HasOne("Entities.Concrete.FakulteEntities.Fakulte", null)
                        .WithMany()
                        .HasForeignKey("FakulteUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AnaDallar_Fakulteler");

                    b.HasOne("Entities.Concrete.FakulteEntities.Fakulte", "Fakulte")
                        .WithMany("AnaDallar")
                        .HasForeignKey("FakulteUuid1");

                    b.Navigation("Fakulte");
                });

            modelBuilder.Entity("Entities.Concrete.FakulteEntities.Bolum", b =>
                {
                    b.HasOne("Entities.Concrete.FakulteEntities.AnaDal", null)
                        .WithMany()
                        .HasForeignKey("AnaDalUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Bolumler_AnaDallar");

                    b.HasOne("Entities.Concrete.FakulteEntities.AnaDal", "AnaDal")
                        .WithMany()
                        .HasForeignKey("AnaDalUuid1");

                    b.Navigation("AnaDal");
                });

            modelBuilder.Entity("Entities.Concrete.FakulteEntities.OgrenciBolumKayit", b =>
                {
                    b.HasOne("Entities.Concrete.FakulteEntities.Bolum", null)
                        .WithMany()
                        .HasForeignKey("BolumUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OgrenciBolumKayit_Bolumler");

                    b.HasOne("Entities.Concrete.FakulteEntities.Bolum", "Bolum")
                        .WithMany("OgrenciKayitlari")
                        .HasForeignKey("BolumUuid1");

                    b.HasOne("Core.Entities.Concrete.OzlukEntities.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("KullaniciUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OgrenciBolumKayit_Kullanicilar");

                    b.HasOne("Core.Entities.Concrete.OzlukEntities.Kullanici", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("OgrenciKullaniciUuid");

                    b.Navigation("Bolum");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("Entities.Concrete.OzlukEntities.Adres", b =>
                {
                    b.HasOne("Core.Entities.Concrete.OzlukEntities.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("KullaniciUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Adresler_Kullanicilar");

                    b.HasOne("Core.Entities.Concrete.OzlukEntities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciUuid1");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Entities.Concrete.OzlukEntities.Eposta", b =>
                {
                    b.HasOne("Core.Entities.Concrete.OzlukEntities.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("KullaniciUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Epostalar_Kullanicilar");

                    b.HasOne("Core.Entities.Concrete.OzlukEntities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciUuid1");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Entities.Concrete.OzlukEntities.Telefon", b =>
                {
                    b.HasOne("Core.Entities.Concrete.OzlukEntities.Kullanici", null)
                        .WithMany()
                        .HasForeignKey("KullaniciUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Telefonlar_Kullanicilar");

                    b.HasOne("Core.Entities.Concrete.OzlukEntities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciUuid1");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Core.Entities.Concrete.OzlukEntities.Kullanici", b =>
                {
                    b.Navigation("KullaniciIslemYetkileri");
                });

            modelBuilder.Entity("Core.Entities.Concrete.YetkiEntities.IslemYetkisi", b =>
                {
                    b.Navigation("KullaniciIslemYetkileri");
                });

            modelBuilder.Entity("Entities.Concrete.DersEntities.Ders", b =>
                {
                    b.Navigation("AkademisyenDersAtamalari");

                    b.Navigation("OgrenciKayitlari");

                    b.Navigation("Sinavlar");
                });

            modelBuilder.Entity("Entities.Concrete.DersEntities.Sinav", b =>
                {
                    b.Navigation("Notlar");
                });

            modelBuilder.Entity("Entities.Concrete.FakulteEntities.Bolum", b =>
                {
                    b.Navigation("AkademisyenAtamalari");

                    b.Navigation("OgrenciKayitlari");
                });

            modelBuilder.Entity("Entities.Concrete.FakulteEntities.Fakulte", b =>
                {
                    b.Navigation("AnaDallar");
                });
#pragma warning restore 612, 618
        }
    }
}
